### ISSUE TITLE
Exception: EventType missing "PAUSE_START"

### ISSUE THREAD

**Issue by wooofwoof** [stelar7/R4J#40]
Hi everyone!
An excepcion just happened to me, just running as usual, maybe too many requests over time...?. 
With lastest version .jar:

```
Exception in thread "main" no.stelar7.api.r4j.basic.exceptions.APIEnumNotUpToDateException: The enum no.stelar7.api.r4j.basic.constants.types.lol.EventType is missing the type "PAUSE_START"!
Please make sure you have the latest version of the library!
If you do, send this message to the maintainer of the API.
	at no.stelar7.api.r4j.basic.serializer.GenericEnumSerializer.lambda$deserialize$2(GenericEnumSerializer.java:23)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at no.stelar7.api.r4j.basic.serializer.GenericEnumSerializer.deserialize(GenericEnumSerializer.java:23)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at no.stelar7.api.r4j.pojo.shared.GAMHSMatch.asLOLTimeline(GAMHSMatch.java:44)
	at no.stelar7.api.r4j.impl.lol.builders.matchv5.match.TimelineBuilder.getTimeline(TimelineBuilder.java:61)
	at SoloScout.getTimelineData(SoloScout.java:696)
	at SoloScout.scoutTo(SoloScout.java:280)
	at SoloScout.scoutTeam(SoloScout.java:367)
	at SoloScout.main(SoloScout.java:989)

Process finished with exit code 1
```
Thank you for the feedback and have a nice day!

**Comment by stelar7** [comment]
Fixed in 2.1.7
