### ISSUE TITLE
getMatchList passes an invalid count to Riot's API

### ISSUE THREAD

**Issue by lbkulinski** [stelar7/R4J#89]
Hello. When using the following code, I get a malformed API request exception:
```
LazyList<String> matchIds = r4J.getLoLAPI()
                               .getMatchAPI()
                               .getMatchList(RegionShard.AMERICAS, puuid);

for (String matchId : matchIds) {
    LOLMatch match = r4J.getLoLAPI()
                        .getMatchAPI()
                        .getMatch(RegionShard.AMERICAS, matchId);

    System.out.println(match);
}
```
The exception is as follows:
```
no.stelar7.api.r4j.basic.exceptions.APIResponseException: Your api request is malformed!
https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/uDobVVhzdpTY556c3rSkv4f24V09sfv1FFcav9qxLf_DigqkWhVHxItKd7swQFoFPsA6ehualCwiGA/ids?start=100&count=200
{"status":{"message":"Bad request - Query parameter 'count' must have a maximum value of 100. Invalid value '200' given.","status_code":400}}
	at no.stelar7.api.r4j.basic.calling.DataCallBuilder.build(DataCallBuilder.java:142) ~[R4J-2.3.4.jar:na]
	at no.stelar7.api.r4j.impl.lol.builders.matchv5.match.MatchListBuilder.get(MatchListBuilder.java:143) ~[R4J-2.3.4.jar:na]
	at no.stelar7.api.r4j.impl.lol.raw.MatchV5API.getMatchList(MatchV5API.java:27) ~[R4J-2.3.4.jar:na]
	at no.stelar7.api.r4j.impl.lol.raw.MatchV5API.lambda$getMatchList$0(MatchV5API.java:42) ~[R4J-2.3.4.jar:na]
	at no.stelar7.api.r4j.basic.utils.LazyList.loadMoreData(LazyList.java:35) ~[R4J-2.3.4.jar:na]
	at no.stelar7.api.r4j.basic.utils.LazyList.access$100(LazyList.java:7) ~[R4J-2.3.4.jar:na]
	at no.stelar7.api.r4j.basic.utils.LazyList$LazyListIterator.hasNext(LazyList.java:155) ~[R4J-2.3.4.jar:na]
	at com.logankulinski.runner.Runner.run(Runner.java:47) ~[classes/:na]
	at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:794) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:782) ~[spring-boot-3.2.1.jar:3.2.1]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:557) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:782) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347) ~[spring-boot-3.2.1.jar:3.2.1]
	at com.logankulinski.Application.main(Application.java:9) ~[classes/:na]
```
As you can see, the request URL is using a count of 200. I believe the maximum count is 100. Am I doing something wrong? Thanks.

**Comment by stelar7** [comment]
Thanks for the report, this is fixed with https://github.com/stelar7/R4J/commit/a2b6221881ab64ff37f23c348c5380c47a9595b8

**Comment by lbkulinski** [comment]
Did something happen in regards to the Maven dependency? When I run it with the new version I get the follow exception:
```
java.lang.NoClassDefFoundError: com/google/gson/JsonObject
	at no.stelar7.api.r4j.basic.constants.api.URLEndpoint.<clinit>(URLEndpoint.java:119) ~[R4J-2.4.1.jar:na]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[na:na]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[na:na]
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340) ~[na:na]
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71) ~[na:na]
	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:154) ~[na:na]
	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:4037) ~[na:na]
	at java.base/java.lang.System$2.getEnumConstantsShared(System.java:2374) ~[na:na]
	at java.base/java.util.EnumMap.getKeyUniverse(EnumMap.java:750) ~[na:na]
	at java.base/java.util.EnumMap.<init>(EnumMap.java:138) ~[na:na]
	at no.stelar7.api.r4j.basic.cache.CacheLifetimeHint.<init>(CacheLifetimeHint.java:21) ~[R4J-2.4.1.jar:na]
	at no.stelar7.api.r4j.basic.cache.CacheLifetimeHint.<clinit>(CacheLifetimeHint.java:38) ~[R4J-2.4.1.jar:na]
	at no.stelar7.api.r4j.basic.cache.impl.FileSystemCacheProvider.<init>(FileSystemCacheProvider.java:22) ~[R4J-2.4.1.jar:na]
	at no.stelar7.api.r4j.basic.cache.impl.FileSystemCacheProvider.<init>(FileSystemCacheProvider.java:45) ~[R4J-2.4.1.jar:na]
	at no.stelar7.api.r4j.impl.R4J.<init>(R4J.java:26) ~[R4J-2.4.1.jar:na]
	at com.logankulinski.runner.Runner.run(Runner.java:31) ~[classes/:na]
	at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:794) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:782) ~[spring-boot-3.2.1.jar:3.2.1]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:557) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:782) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347) ~[spring-boot-3.2.1.jar:3.2.1]
	at com.logankulinski.Application.main(Application.java:9) ~[classes/:na]
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 38 common frames omitted
```
Adding the GSON dependency fixes this, but it was not required before. Thanks!
